all:
  hosts:
    web01:
      ansible_host: 172.31.30.50
    web02:
      ansible_host: 172.31.17.154
    db01:
      ansible_host: 172.31.16.165

  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    dc_oregon:
      children:
        webservers:
        dbservers:
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: clientkey.pem